[package]
name = "pulse"
version = "0.1.0"
edition = "2021"
authors = ["Meshack Bahati Ouma <bahatikylemeshack@gmail.com>"]
description = "Request metrics dashboard on Toxi"
license = "Apache-2.0"

[dependencies]
toxi = { version = "3", features = ["full"] }
toxi-core = "3"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
http = "1"
http-body-util = "0.1"
bytes = "1"
toxi-template = "3"
tower = { version = "0.5", features = ["full"] }
toxi-utils = "3"
